server:
  port: 8082

spring:
  application:
    name: "TRANSPORT"
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://;serverName=185.10.75.106;databaseName=way;encrypt=true;trustServerCertificate=true;
    username: sa
    password: ahmadi@102030
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: false
    cloud:
      openfeign:
        client:
          config:
            default:
              loggerLevel: full

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

PageRequest :
  page : 0
  size : 10