server:
  port: 8082

spring:
  application:
    name: "TRANSPORT"
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://;serverName=localhost;databaseName=way;encrypt=true;trustServerCertificate=true;
    username: sa
    password: asd123!@#
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: false
    cloud:
      openfeign:
        client:
          config:
            default:
              loggerLevel: full

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

PageRequest :
  page : 0
  size : 10

map:
  neshan:
    api-key: service.e476c7ad491c4c56a8faae2e104fba21
    base-url: https://api.neshan.org

springdoc:
  swagger-ui:
    path: index.html
    server-url: http://localhost:8083
    #    server-url: http://ctiran.ir
    enabled: true
    config-url: /transportSwagger/v3/api-docs/swagger-config
    disable-swagger-default-url: true
    url: /transportSwagger/v3/api-docs

